import random


sticker_pack = [
    'CAACAgIAAxkBAAEIOcdkGgug48Ul5SHOW09YxIY_xiYAARQAAhkAA3PkXwhXwaOHakML3C8E',
    'CAACAgIAAxkBAAEIOclkGgunmDocn_Mp3zUH6VhxvmSC0QACGwADc-RfCEN7qoSGwxFyLwQ',
    'CAACAgIAAxkBAAEIOctkGgutHsu1y_Rma7-W8Q1Wy2BojQACHQADc-RfCD2t7iRAE04qLwQ',
    'CAACAgIAAxkBAAEIOc9kGgvnYhoiR8F_4rdrD5hmbdTsfwACHwADc-RfCF7y3yeeok7TLwQ',
    'CAACAgIAAxkBAAEIOdFkGgv73kOmUZEKsRvvoZjmAVkHSwACJwADc-RfCNZQNeCom5LZLwQ',
    'CAACAgIAAxkBAAEIOdNkGgwJ3aJSGG33TEoqQBCh3R6nrAACtwADc-RfCHba2mHwCKk6LwQ',
    'CAACAgIAAxkBAAEIOdVkGgwWKfIXwg93ZevhPrnmAbBSNAACMwEAAnPkXwgb7gLyMAtvXi8E',
    'CAACAgIAAxkBAAEIOdlkGgwrWWBF4-XVB8nn3COkIWGUKQACRwADc-RfCC2eFqb0hQ9tLwQ',
    'CAACAgIAAxkBAAEIOdtkGgw7-lO9VcYpzf3tnxnQ2VEYPQACvQADc-RfCP9G2zAeMFwsLwQ',
    'CAACAgIAAxkBAAEIOd1kGgxMEzoj-fgZu1oo7PriKFX__QACGgEAAnPkXwicdj1bGEjDky8E',
    'CAACAgIAAxkBAAEIOd9kGgxebAJcdbdaxKfTPL28c-71NgACKwADc-RfCFyCHYkJJ5AYLwQ',
    'CAACAgIAAxkBAAEIOeFkGgxyepX_OVm7IYeik03gLxXrOAAC5wIAAnPkXwgYL02tKq4KuS8E',
    'CAACAgIAAxkBAAEIOeNkGgyF7RKFbegEEz7Rgx2o4opKQAACIAMAAnPkXwgxVxY4FyApvC8E',
    'CAACAgQAAxkBAAEIOeVkGgyxpnTd5oFwR4F3uYj7NIoDRwACbQwAAopuaVDwejJs6ciEiS8E',
    'CAACAgQAAxkBAAEIOedkGgzNh2zUn39OyM9vzSmPqdmGqwACZwwAAoZfcFCL9YJDuiiPrS8E',
    'CAACAgQAAxkBAAEIOelkGgzihmoir-msjvkMW22P7kfeWAACuwwAAsPWaFCsjmjDuCHami8E',
    'CAACAgQAAxkBAAEIOetkGgzl6DzIZp6mPRYcjVTWscngJgACzwoAAhBwcVDOOxPcKuoXcy8E',
    'CAACAgQAAxkBAAEIOe1kGgzotgdGhk5yW8yEOU3z43Wc5QACDAsAAsEecVA3ur4V990ofC8E',
    'CAACAgQAAxkBAAEIOe5kGgzp_IPeoW7QjPguKo5qJ_GHLwACZA0AAuR5cFAyuz5viZElby8E',
    'CAACAgQAAxkBAAEIOfBkGgzqK6170t33Yh0zk1FpaiaZDwACEQwAAoqecVBUrf-d4e-bHS8E',
    'CAACAgQAAxkBAAEIOfNkGgztBXw9TJppaMere1mXMljSEwACnwoAAvyraFAWUUz8BS1Kui8E',
    'CAACAgQAAxkBAAEIOfVkGgzuahM-NWMLPHuDdORA_4U_YAACewsAAl6ocVCkdVg4e2JEWS8E',
    'CAACAgQAAxkBAAEIOfdkGgzxZXKiEYXx8ae1WnlmL6_LvAACxwoAArvhaVCpe8PvtCre5y8E',
    'CAACAgQAAxkBAAEIOflkGgz5QsKk7YPsY_clRf7w0saQcAAC-woAAsmpaVAxJ6SBriYrci8E'
    ]


def get_random_sticker():
    return random.choice(sticker_pack)
